More complete set of python bindings for G3Timestream and friends
CMB-S4/spt3g_software pull request #84
Opened 2022-08-25 22:31 UTC by arahlin

* Implement binary and unary ufuncs for G3Timestream, G3VectorDouble and DoubleVector,
  to enable arithmetic operations involving these types or scalars or numpy arrays
  on either side of each operator.
* Binary functions involving G3VectorInt and IntVector are incomplete,
  as some operations are likely to return arrays of a different type.
* Implement bindings for G3TimestreamMap that mimic the behavior of SO's G3SuperTimestream
  objects (.times, .data, .names properties).

Fixes #83 (as much as possible)

2022-08-29 14:26 UTC, mhasself approved these changes
G3TimestreamMap extensions look great!  Thanks.

2022-09-16 13:42 UTC, nwhitehorn requested changes
Looks great aside from the one nit.

2022-09-16 13:42 UTC, nwhitehorn commented on core/python/timestreamextensions.py
> +    is_g3 = 'G3' in a.__class__.__name__ or 'G3' in b.__class__.__name__
Maybe check if it is a kind of G3FrameObject instead? I think that's the actual test you want to do here.

For example,
```suggestion
    is_g3 = issubclass(a, core.G3FrameObject) or issubclass(b, core.G3FrameObject)
```

2022-09-16 18:46 UTC, nwhitehorn approved these changes

2022-09-16 19:01 UTC, merged